* Description
Useful Emacs Lisp and Common Lisp macros and functions.

(For me "Common Lisp" means [[http://sbcl.org/][sbcl]]; part of the CL-code will probably not work in other CL dialects.)

The (main) file [[file:shalaev.org][shalaev.org]] contains
- source code,
- examples, and
- tests

for both elisp and Common Lisp macros and functions.

* Quick start
** Emacs Lisp code
Either
- copy-paste or load [[file:generated][generated/]]*.el into your projects, or

- load the code as a package:
  1. copy [[file:packaged/shalaev.el][shalaev.el]] into =~/.emacs.d/local-packages/=,
  2. load [[file:packaged/start.el][start.el]] from [[file:generated/dot.emacs][~/.emacs]], and
  3. =(require 'shalaev)= in your el-code.

For usage example, see the [[https://github.com/chalaev/cloud][cloud (sync)]] project.
** Common Lisp code
Unpack [[file:packaged/cl-shalaev.tbz][cl-shalaev.tbz]] into your [[https://www.quicklisp.org/beta/][Quicklisp]] directory:\\
=tar xjfv cl-shalaev.tbz --directory=$HOME/quicklisp/local-projects/=

and =(require 'shalaev)= in your code.

For usage example, see the [[https://github.com/chalaev/cl-simple-logger][simple-logger]] project.

* License
This code is released under [[file:LICENSE.txt][MIT license]].
